flecha_xpm = [  
"76 76 281 2",
"  	c None",
". 	c #FFFFFF",
"+ 	c #FCE7D6",
"@ 	c #F19445",
"# 	c #ED7613",
"$ 	c #FBE3CE",
"% 	c #F08F3E",
"& 	c #EC710B",
"* 	c #FBE0CA",
"= 	c #F08C39",
"- 	c #EC710A",
"; 	c #FBE4D0",
"> 	c #EB710A",
", 	c #EF903F",
"' 	c #EC7412",
") 	c #EB700A",
"! 	c #EB7412",
"~ 	c #EA700A",
"{ 	c #EA7411",
"] 	c #E96F09",
"^ 	c #D07C36",
"/ 	c #C18451",
"( 	c #DF741B",
"_ 	c #E97311",
": 	c #E86E09",
"< 	c #AD8E75",
"[ 	c #ABABAB",
"} 	c #BCBCBC",
"| 	c #B0B0B0",
"1 	c #ACACAC",
"2 	c #9E9E9E",
"3 	c #C08451",
"4 	c #C6C6C6",
"5 	c #F2F2F2",
"6 	c #E8E8E8",
"7 	c #E5E5E5",
"8 	c #EFEFEF",
"9 	c #E6E6E6",
"0 	c #CECECE",
"a 	c #E87311",
"b 	c #E76E09",
"c 	c #CCCCCC",
"d 	c #E87210",
"e 	c #E76D08",
"f 	c #C08351",
"g 	c #E77210",
"h 	c #E66D08",
"i 	c #AC8E75",
"j 	c #E0E0E0",
"k 	c #BF8351",
"l 	c #DEDEDE",
"m 	c #E77110",
"n 	c #E66C08",
"o 	c #D9D9D9",
"p 	c #E67110",
"q 	c #E56C08",
"r 	c #D3D3D3",
"s 	c #E5710F",
"t 	c #E46C07",
"u 	c #AC8E74",
"v 	c #BE8350",
"w 	c #E5700F",
"x 	c #E46B07",
"y 	c #AC8D74",
"z 	c #D4D4D4",
"A 	c #BE8250",
"B 	c #E4700F",
"C 	c #E36B07",
"D 	c #E3E3E3",
"E 	c #E46F0F",
"F 	c #E36A07",
"G 	c #E36F0F",
"H 	c #E26A07",
"I 	c #AB8D74",
"J 	c #E7E7E7",
"K 	c #D0D0D0",
"L 	c #CDCDCD",
"M 	c #BD8250",
"N 	c #E36F0E",
"O 	c #E26A06",
"P 	c #B08A6B",
"Q 	c #999999",
"R 	c #E9E9E9",
"S 	c #D1D1D1",
"T 	c #CFCFCF",
"U 	c #C27F47",
"V 	c #E26E0E",
"W 	c #E16906",
"X 	c #CF752B",
"Y 	c #CBCBCB",
"Z 	c #EAEAEA",
"` 	c #DFDFDF",
" .	c #D2D2D2",
"..	c #DCDCDC",
"+.	c #A6A6A6",
"@.	c #9E9690",
"#.	c #DC6C0F",
"$.	c #C67B3D",
"%.	c #9C9C9C",
"&.	c #EEEEEE",
"*.	c #ECECEC",
"=.	c #EBEBEB",
"-.	c #E4E4E4",
";.	c #DADADA",
">.	c #D7D7D7",
",.	c #D6D6D6",
"'.	c #D5D5D5",
").	c #DDDDDD",
"!.	c #DBDBDB",
"~.	c #D37222",
"{.	c #E16E0E",
"].	c #E06906",
"^.	c #B88458",
"/.	c #A1A1A1",
"(.	c #F0F0F0",
"_.	c #D8D8D8",
":.	c #C7C7C7",
"<.	c #C57B3D",
"[.	c #E16D0E",
"}.	c #E06806",
"|.	c #B48762",
"1.	c #A5A5A5",
"2.	c #C17E47",
"3.	c #E06D0E",
"4.	c #DF6806",
"5.	c #DB6B0F",
"6.	c #A6907D",
"7.	c #B3B3B3",
"8.	c #E1E1E1",
"9.	c #B38762",
"0.	c #E06D0D",
"a.	c #DF6805",
"b.	c #DB6B0E",
"c.	c #A29386",
"d.	c #BABABA",
"e.	c #EDEDED",
"f.	c #E2E2E2",
"g.	c #A4A4A4",
"h.	c #E06C0D",
"i.	c #DF6705",
"j.	c #D27021",
"k.	c #9D9690",
"l.	c #C8C8C8",
"m.	c #F3F3F3",
"n.	c #AFAFAF",
"o.	c #DB6A0E",
"p.	c #DF6C0D",
"q.	c #DE6705",
"r.	c #CD742A",
"s.	c #F4F4F4",
"t.	c #BBBBBB",
"u.	c #D17021",
"v.	c #C47A3D",
"w.	c #CACACA",
"x.	c #DE6B0D",
"y.	c #DD6605",
"z.	c #B78358",
"A.	c #F1F1F1",
"B.	c #C3793D",
"C.	c #DE6B0C",
"D.	c #DD6604",
"E.	c #B38661",
"F.	c #DD6B0C",
"G.	c #DC6604",
"H.	c #D8690D",
"I.	c #A68F7D",
"J.	c #AA8C74",
"K.	c #DD6A0C",
"L.	c #DC6504",
"M.	c #D8680D",
"N.	c #A19286",
"O.	c #F5F5F5",
"P.	c #F6F6F6",
"Q.	c #ADADAD",
"R.	c #CF6F20",
"S.	c #F8F8F8",
"T.	c #F9F9F9",
"U.	c #F7F7F7",
"V.	c #B9B9B9",
"W.	c #D46C17",
"X.	c #DC6A0C",
"Y.	c #DB6504",
"Z.	c #CA7229",
"`.	c #C9C9C9",
" +	c #FAFAFA",
".+	c #FBFBFB",
"++	c #DC690C",
"@+	c #DB6404",
"#+	c #C2783C",
"$+	c #FDFDFD",
"%+	c #FEFEFE",
"&+	c #DB690B",
"*+	c #DA6403",
"=+	c #B68257",
"-+	c #FCFCFC",
";+	c #B18561",
">+	c #9F9F9F",
",+	c #A2A2A2",
"'+	c #DA690B",
")+	c #D96403",
"!+	c #D36103",
"~+	c #CE5F03",
"{+	c #C35A03",
"]+	c #C05903",
"^+	c #B85503",
"/+	c #AF560C",
"(+	c #9D8B7D",
"_+	c #A8A8A8",
":+	c #AB540C",
"<+	c #AF5102",
"[+	c #DA680B",
"}+	c #D96303",
"|+	c #CE5E03",
"1+	c #C35903",
"2+	c #B85403",
"3+	c #AF5002",
"4+	c #AD4F02",
"5+	c #AB530C",
"6+	c #9C9087",
"7+	c #B1B1B1",
"8+	c #B4B4B4",
"9+	c #9A948F",
"0+	c #BD5603",
"a+	c #A95D1F",
"b+	c #C3C3C3",
"c+	c #D9680B",
"d+	c #D86303",
"e+	c #D05F03",
"f+	c #B75403",
"g+	c #AC4F02",
"h+	c #A76128",
"i+	c #A66631",
"j+	c #D9670A",
"k+	c #D86202",
"l+	c #C75A02",
"m+	c #AC4E02",
"n+	c #A56A3A",
"o+	c #A36F44",
"p+	c #D8670A",
"q+	c #D76202",
"r+	c #D46102",
"s+	c #AB4E02",
"t+	c #A17857",
"u+	c #A07D60",
"v+	c #CF5E02",
"w+	c #9C8B7D",
"x+	c #B45202",
"y+	c #AA530B",
"z+	c #A2744D",
"A+	c #D7660A",
"B+	c #D66102",
"C+	c #D36002",
"D+	c #B55202",
"E+	c #AA4D02",
"F+	c #CB5C02",
"G+	c #D05E02",
"H+	c #C35802",
"I+	c #D66509",
"J+	c #D56001",
"K+	c #CA5B01",
"L+	c #BF5601",
"M+	c #B75201",
"N+	c #B25001",
"O+	c #AA4C01",
"P+	c #D25F01",
"Q+	c #B95401",
"R+	c #B45101",
"S+	c #D56509",
"T+	c #D46001",
"U+	c #DD8238",
"V+	c #F7E0CE",
"W+	c #D45F01",
"X+	c #DC7E32",
"Y+	c #F6DCC8",
"Z+	c #D35F01",
"`+	c #F6DECB",
" @	c #DC8034",
".@	c #D35F00",
"+@	c #F8E4D4",
"@@	c #DE853D",
"#@	c #D46408",
". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
". . . . . . . + @ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # @ + . . . . . . . ",
". . . . . $ % & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & % $ . . . . . ",
". . . . * & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & * . . . . ",
". . . . = - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - = . . . . ",
". . . ; > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > ; . . . ",
". . . , > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > , . . . ",
". . . ' ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ' . . . ",
". . . ' ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ' . . . ",
". . . ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ! . . . ",
". . . ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ! . . . ",
". . . ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ! . . . ",
". . . { ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] { . . . ",
". . . { ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] { . . . ",
". . . { ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ^ / / / / / / / / / / / / / / / / / / / / / / / ( ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] { . . . ",
". . . _ : : : : : : : : : : : : : : : : : : : : : < [ } } } } } } } } } } } } } } } } } } } | 1 2 3 : : : : : : : : : : : : : : : : : : : : : : _ . . . ",
". . . _ : : : : : : : : : : : : : : : : : : : : : < 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 7 1 3 : : : : : : : : : : : : : : : : : : : : : : _ . . . ",
". . . _ : : : : : : : : : : : : : : : : : : : : : < 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 0 7 1 3 : : : : : : : : : : : : : : : : : : : : : : _ . . . ",
". . . a b b b b b b b b b b b b b b b b b b b b b < 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 c 7 1 3 b b b b b b b b b b b b b b b b b b b b b b a . . . ",
". . . d e e e e e e e e e e e e e e e e e e e e e < 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 c 7 1 f e e e e e e e e e e e e e e e e e e e e e e d . . . ",
". . . g h h h h h h h h h h h h h h h h h h h h h i 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 j c 7 1 k h h h h h h h h h h h h h h h h h h h h h h g . . . ",
". . . g h h h h h h h h h h h h h h h h h h h h h i 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 l c 7 1 k h h h h h h h h h h h h h h h h h h h h h h g . . . ",
". . . m n n n n n n n n n n n n n n n n n n n n n i 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 o c 7 1 k n n n n n n n n n n n n n n n n n n n n n n m . . . ",
". . . p q q q q q q q q q q q q q q q q q q q q q i 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 r c 7 1 k q q q q q q q q q q q q q q q q q q q q q q p . . . ",
". . . p q q q q q q q q q q q q q q q q q q q q q i 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 c c 7 1 k q q q q q q q q q q q q q q q q q q q q q q p . . . ",
". . . s t t t t t t t t t t t t t t t t t t t t t u 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 l c c 7 1 v t t t t t t t t t t t t t t t t t t t t t t s . . . ",
". . . w x x x x x x x x x x x x x x x x x x x x x y 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 z c c 7 1 A x x x x x x x x x x x x x x x x x x x x x x w . . . ",
". . . B C C C C C C C C C C C C C C C C C C C C C y 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 D c c c 7 1 A C C C C C C C C C C C C C C C C C C C C C C B . . . ",
". . . B C C C C C C C C C C C C C C C C C C C C C y 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 z c c c 7 1 A C C C C C C C C C C C C C C C C C C C C C C B . . . ",
". . . E F F F F F F F F F F F F F F F F F F F F F y 4 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 l c c c c 7 1 A F F F F F F F F F F F F F F F F F F F F F F E . . . ",
". . . G H H H H H H H H H H H H H H H H H H H H H I 4 8 9 9 9 9 9 9 9 J J J J J J D K 0 0 L L 7 1 M H H H H H H H H H H H H H H H H H H H H H H G . . . ",
". . . N O O O O O O O O O O O P Q Q Q Q Q Q Q Q Q Q 4 8 9 9 9 9 J J 6 6 6 6 R R D r S S K K T 9 1 Q Q Q Q Q Q Q Q Q Q U O O O O O O O O O O O O N . . . ",
". . . V W W W W W W W W W W W X Q Y R R R R R R R R 8 8 9 J J 6 6 R R R Z Z Z ` z z z z r r  .J ..r r  . . . . . .+.@.#.W W W W W W W W W W W W V . . . ",
". . . V W W W W W W W W W W W W $.%...5 &.*.*.*.*.*.*.=.J 6 6 R R Z Z =.=.-.;.>.>.>.>.,.,.'.z l ).)...!.;.o ).7 } @.~.W W W W W W W W W W W W W V . . . ",
". . . {.].].].].].].].].].].].].].^./.J (.J 9 9 9 9 J 6 6 R Z Z =.=.*.7 ..o ;.;.;.;.o o o _.>.,.'.z r S K r -.:.Q <.].].].].].].].].].].].].].].{.. . . ",
". . . [.}.}.}.}.}.}.}.}.}.}.}.}.}.}.|.1.=.(.9 9 9 J 6 R Z Z =.*.*.6 l !.....).).).).....!.;.;.o _.,.'.z z -.z %.2.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.[.. . . ",
". . . 3.4.4.4.4.4.4.4.4.4.4.4.4.4.4.5.6.7.(.&.9 J 6 R Z =.=.*.*.8...).l ` ` ` j j ` ` ` l )...!.;.o >.,.7 ..2 9.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.3.. . . ",
". . . 0.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.b.c.d.5 e.6 R Z =.*.*.Z ).).` j 8.8.f.f.f.f.f.f.8.8.j ` l ..!.o -.7 g.6.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.0.. . . ",
". . . h.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.j.k.l.m.e.Z =.*.e.Z l l j 8.f.D -.-.7 7 7 7 -.-.D f.8.j ` ).D Z n.c.o.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.h.. . . ",
". . . p.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.r.Q ,.s.e.*.e.*.l ` 8.f.D 7 9 9 J 6 6 6 6 J 9 9 7 -.f.8.7 &.t.k.u.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.p.. . . ",
". . . p.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.v.%.l s.&.&.f.` 8.D -.9 J 6 R Z Z =.=.Z Z R 6 J 9 -.9 8 w.Q r.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.p.. . . ",
". . . x.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.z.g.Z s.6 ` 8.D 7 9 6 R =.*.e.e.e.e.e.e.*.=.R 6 J A.,.Q B.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.x.. . . ",
". . . C.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.E.1.A.*.8.D 7 9 6 Z =.e.&.8 (.(.(.(.8 &.e.*.=.A.f.%.E.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.C.. . . ",
". . . F.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.H.I.1 R =.-.9 6 Z *.e.8 A.5 m.m.m.m.5 A.8 &.5 *.1.J.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.F.. . . ",
". . . K.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.M.N.n.&.=.J R =.e.8 A.m.s.O.P.P.O.s.m.A.s.m.Q.I.M.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.K.. . . ",
". . . K.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.R.k.d.5 *.Z *.8 A.m.O.P.S.T.T.S.U.O.O.S.V.k.W.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.K.. . . ",
". . . X.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Z.Q `.s.e.e.8 5 s.P.S. +.+.+ +S.U.T.4 Q R.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.X.. . . ",
". . . ++@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+#+Q '.s.8 (.5 s.U.T..+$+%+.+ +.+o Q #+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+++. . . ",
". . . &+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+=+%.8.s.(.5 s.P.T..+-+$+.+.+7 %.=+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+&+. . . ",
". . . &+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+;+>+=.O.A.m.O.U.T. + +.+8 ,+;+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+&+. . . ",
". . . '+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+!+~+{+]+^+^+/+(+_+(.O.5 s.O.P.U. +s.[ (+:+<+^+^+{+{+~+!+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+)+'+. . . ",
". . . [+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+|+1+2+3+4+4+4+4+4+4+4+5+6+7+s.s.5 m.s.P. +8+9+5+4+4+4+4+4+4+4+4+3+2+1+|+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+. . . ",
". . . [+}+}+}+}+}+}+}+}+}+}+}+}+}+|+0+3+4+4+4+4+4+4+4+4+4+4+4+4+a+9+} P.5 (.m.S.b+9+a+4+4+4+4+4+4+4+4+4+4+4+4+4+3+0+|+}+}+}+}+}+}+}+}+}+}+}+}+}+[+. . . ",
". . . c+d+d+d+d+d+d+d+d+d+d+d+e+f+g+g+g+g+g+g+g+g+g+g+g+g+g+g+g+g+h+Q Y P.A.P.S Q i+g+g+g+g+g+g+g+g+g+g+g+g+g+g+g+g+g+f+e+d+d+d+d+d+d+d+d+d+d+d+c+. . . ",
". . . j+k+k+k+k+k+k+k+k+k+k+l+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+n+Q '.O.` %.o+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+m+l+k+k+k+k+k+k+k+k+k+k+j+. . . ",
". . . p+q+q+q+q+q+q+q+q+q+r+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+t+%.T >+u+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+r+q+q+q+q+q+q+q+q+q+p+. . . ",
". . . p+q+q+q+q+q+q+q+q+q+v+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+u+Q w+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+v+q+q+q+q+q+q+q+q+q+p+. . . ",
". . . p+q+q+q+q+q+q+q+q+q+q+x+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+y+z+y+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+s+x+q+q+q+q+q+q+q+q+q+q+p+. . . ",
". . . A+B+B+B+B+B+B+B+B+B+B+C+D+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+D+C+B+B+B+B+B+B+B+B+B+B+A+. . . ",
". . . A+B+B+B+B+B+B+B+B+B+B+B+B+F+D+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+D+F+B+B+B+B+B+B+B+B+B+B+B+B+A+. . . ",
". . . A+B+B+B+B+B+B+B+B+B+B+B+B+B+B+G+H+D+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+E+D+H+G+B+B+B+B+B+B+B+B+B+B+B+B+B+B+A+. . . ",
". . . I+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+K+L+M+N+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+O+N+M+L+K+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+I+. . . ",
". . . I+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+P+K+K+L+L+L+Q+R+R+R+R+R+R+R+R+Q+L+L+L+K+K+P+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+I+. . . ",
". . . I+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+J+I+. . . ",
". . . S+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+S+. . . ",
". . . U+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+T+U+. . . ",
". . . V+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+V+. . . ",
". . . . X+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+W+X+. . . . ",
". . . . Y+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Z+Y+. . . . ",
". . . . . `+ @.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@ @`+. . . . . ",
". . . . . . . +@@@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@#@@@+@. . . . . . . ",
". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . "]
